### ISSUE TITLE
ModuleNotFoundError: No module named 'kqs'

### ISSUE THREAD

**Issue by docentYT** [OSMChina/Keqing#17]
I installed the package using the `pip install keqing-sword` command but python keeps saying that the module 'kqs' not found when I am trying to import `Waifu` as specified in the documentation:
```py
from kqs.waifu import Waifu
```

**Comment by LaoshuBaby** [comment]
Ah, it seems that this problem has indeed occurred. It started after version 0.7.0. This problem did not exist in the last stable version 0.6.0. It is speculated that it was caused by switching to poetry system to complete the package building process after 0.7.0. , but I have no idea how poetry causes this problem. Since the core functions have not changed much, I temporarily recommend everyone to use 0.6.0

Thank you for discovering this question, I will continue to pay attention
